### ISSUE TITLE
Improve the website style

### ISSUE THREAD

**Issue by Wytamma** [codertsv/codertsv.github.io#2]
The current website ([https://codertsv.github.io/](https://codertsv.github.io/)) could use some TLC. Does anyone have some ideas or examples for a good group landing page? Ideally it would be something a bit more eye catching than a pure markdown render, but simple enough that we can still easily add content.

**Comment by BooteCG** [comment]
No sorry, I don’t have much experience with building websites. How would you do that? Is that done using Shiny? I know Kevin said he’s good at that so I could ask him?

**Comment by iracooke** [comment]
I definitely agree that it needs some work to make it look nicer but I would suggest sticking with a static site since that will allow us to host it on github.  As far as I know Shiny requires server-side code to run so it will not work on github.

Github have some starting themes for github pages sites and we could just take one of those and tweak it. 

@BooteCG even if you haven't got much experience with websites I think it would still be helpful to have suggestions about content .. or maybe point us towards website we could try to emulate.

**Comment by BooteCG** [comment]
Good point @iracooke. I'll have a look through some examples and see what I can think up :)

**Comment by ecolology** [comment]
Not sure if this is what you're looking for Ira (or if you've already mentioned it at the meeting), but the prettydoc package is an easy way to beautify Rmarkdown renders quickly. Only con I've noticed is reduced functionality with some other .html-knit features (e.g., floating table of contents is not compatible)
https://prettydoc.statr.me/themes.html

**Comment by Wytamma** [comment]
I agree with Ira that we should stick with something static. 

@ecolology prettydoc looks cool! I'll have to try it for my Rmarkdown files. The only problem is that we'd have to set up some continuous integration service like [GitHub Actions](https://github.com/features/actions) or [Travis CI](https://travis-ci.org/) to build (knit) the site with every push to the repo. That's totally possible (even easy with actions)! However, it might be even easier to stick with default [Github-pages](https://pages.github.com/) build system ([Jekyll based](https://help.github.com/en/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll)). We can just add theme over the top of our current markdown site e.g. one of [these default themes](https://pages.github.com/themes/) (they are similar to the prettydoc themes anyway) or we could clone another more feature complete theme e.g. [beautiful-jekyll](https://github.com/daattali/beautiful-jekyll) and customise it for our needs.

There's a big a list of [Jekyll themes here](https://github.com/topics/jekyll-theme) for those interested.

**Comment by MboiTui** [comment]
Hello there.

I am keen to try and implement one of the jekyll themes Wytamma suggested. If you guys want to give a list of some of your favourite themes, we can have a quick thumbs up poll and see which one to implement to start with?

**Comment by Wytamma** [comment]
I think if you can get a jekyll site working then swapping themes isn't a hassle. Something with a general `_posts` and `_pages` layout would be a great start and a big step up from what we've currently got. I'm happy for you to take the lead on this I you like, but don't feel any pressure, nothing is permanent :)

**Comment by MboiTui** [comment]
Sweet, I'll have a try over the next couple of weeks then!!

**Comment by MboiTui** [comment]
Okay, getting there slowly (See images below, currently within one of my github repositories, haven't committed anything yet)

I am struggling a bit to figure out some things (e.g., with the minima theme I had the about page on the top right. I then switched theme and the about page is not there, but I can't located the html or config file where that's 'coded'.). I guess it's a matter of getting used to html and jekyll. 

<img width="877" alt="Screenshot 2020-06-02 08 50 25" src="https://user-images.githubusercontent.com/26472198/83465150-4bbe7e80-a4b6-11ea-95fe-555db1de7468.png">

<img width="1064" alt="Screenshot 2020-06-02 09 49 22" src="https://user-images.githubusercontent.com/26472198/83465163-5b3dc780-a4b6-11ea-81f0-c21a57113c1b.png">

**Comment by Wytamma** [comment]
Nice man! it's looking so much better already. It's is complex, there's a lot on moving parts in these site generators despite being 'static' 😆 . Basically (in minima) there is a `header_pages` definition in the config and the `header.html` template uses that to build the header. It's a little hard to type though but maybe we can meet on zoom and go over it?

**Comment by MboiTui** [comment]
Yeah that would be helpful. 

I was looking for something like that but could not find it :/
I will look at a few more online resources in the mean time to try and fill in the gaps

I'll write you on fb to arrange a zoom

**Comment by Wytamma** [comment]
I'm going to close this issue with the merging of #16. I will create new issues for the comments you have raised above.
