### ISSUE TITLE
R block block style not rendering

### ISSUE THREAD

**Issue by Wytamma** [codertsv/codertsv.github.io#5]
The `R` code blocks are not rendering properly on the website (https://codertsv.github.io/loops#r) although they are rendering when you view the markdown page by itself (https://github.com/codertsv/codertsv.github.io/blob/master/loops.md#r).

**Comment by BooteCG** [comment]
The parts following step1, step2 etc? On the .md it’s in a big chunk but on the website it’s taken the '#step 1' as a title.
a) move the parentheses following ```r{} down a line 
B) change it to ```{r} (think this is what it’s meant to be?)
C) make each step its own r chunk and use the # as titles. 

It’s not mine so I feel rude just changing it as I’m not sure how people want it set up?

**Comment by Wytamma** [comment]
I fixed it! It was the extra '{}'. I've committed the changes (487b7e38da3134201eb0291d0d0ceacc3d22627a) and will close this issue. Thanks @BooteCG :)
