### ISSUE TITLE
Re-arrange past presentation page

### ISSUE THREAD

**Issue by MboiTui** [codertsv/codertsv.github.io#52]
As of now the past presentation page is hard to navigate. We should add an option to filter by tag/author/etc and also sort by date.

**Comment by Wytamma** [comment]
Isn’t it filtered by tag and year at the moment?

![E65B7BE7-BD96-4703-96F7-E82D992D1027](https://user-images.githubusercontent.com/13726005/159223068-7d2d7a24-6d4b-48a8-bf75-5dff79e5563c.png)
